package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private Integer numeroCompte;
	private Personnel personnel;
	private String login;
	private String motDePasse;
	private Set<Personnel> personnels = new HashSet<Personnel>(0);

	public Compte() {
	}

	public Compte(Personnel personnel, String login, String motDePasse,
			Set<Personnel> personnels) {
		this.personnel = personnel;
		this.login = login;
		this.motDePasse = motDePasse;
		this.personnels = personnels;
	}

	public Integer getNumeroCompte() {
		return this.numeroCompte;
	}

	public void setNumeroCompte(Integer numeroCompte) {
		this.numeroCompte = numeroCompte;
	}

	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

}
