package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Departement generated by hbm2java
 */
public class Departement implements java.io.Serializable {

	private Integer numeroDepartement;
	private String nomDepartement;
	private Set<Personnel> personnels = new HashSet<Personnel>(0);

	public Departement() {
	}

	public Departement(String nomDepartement, Set<Personnel> personnels) {
		this.nomDepartement = nomDepartement;
		this.personnels = personnels;
	}

	public Integer getNumeroDepartement() {
		return this.numeroDepartement;
	}

	public void setNumeroDepartement(Integer numeroDepartement) {
		this.numeroDepartement = numeroDepartement;
	}

	public String getNomDepartement() {
		return this.nomDepartement;
	}

	public void setNomDepartement(String nomDepartement) {
		this.nomDepartement = nomDepartement;
	}

	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

}
