package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Entretien generated by hbm2java
 */
public class Entretien implements java.io.Serializable {

	private Integer numeroEntretien;
	private Typeentretien typeentretien;
	private Date dateArrive;
	private Date dateDepart;
	private Float coutTotal;
	private Integer dureeEntretien;

	public Entretien() {
	}

	public Entretien(Typeentretien typeentretien, Date dateArrive,
			Date dateDepart, Float coutTotal, Integer dureeEntretien) {
		this.typeentretien = typeentretien;
		this.dateArrive = dateArrive;
		this.dateDepart = dateDepart;
		this.coutTotal = coutTotal;
		this.dureeEntretien = dureeEntretien;
	}

	public Integer getNumeroEntretien() {
		return this.numeroEntretien;
	}

	public void setNumeroEntretien(Integer numeroEntretien) {
		this.numeroEntretien = numeroEntretien;
	}

	public Typeentretien getTypeentretien() {
		return this.typeentretien;
	}

	public void setTypeentretien(Typeentretien typeentretien) {
		this.typeentretien = typeentretien;
	}

	public Date getDateArrive() {
		return this.dateArrive;
	}

	public void setDateArrive(Date dateArrive) {
		this.dateArrive = dateArrive;
	}

	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	public Float getCoutTotal() {
		return this.coutTotal;
	}

	public void setCoutTotal(Float coutTotal) {
		this.coutTotal = coutTotal;
	}

	public Integer getDureeEntretien() {
		return this.dureeEntretien;
	}

	public void setDureeEntretien(Integer dureeEntretien) {
		this.dureeEntretien = dureeEntretien;
	}

}
