package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SousTypeEntretien generated by hbm2java
 */
public class SousTypeEntretien implements java.io.Serializable {

	private Integer numeroSousType;
	private String description;
	private Float prixSousType;
	private Set<Typeentretien> typeentretiens = new HashSet<Typeentretien>(0);

	public SousTypeEntretien() {
	}

	public SousTypeEntretien(String description, Float prixSousType,
			Set<Typeentretien> typeentretiens) {
		this.description = description;
		this.prixSousType = prixSousType;
		this.typeentretiens = typeentretiens;
	}

	public Integer getNumeroSousType() {
		return this.numeroSousType;
	}

	public void setNumeroSousType(Integer numeroSousType) {
		this.numeroSousType = numeroSousType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrixSousType() {
		return this.prixSousType;
	}

	public void setPrixSousType(Float prixSousType) {
		this.prixSousType = prixSousType;
	}

	public Set<Typeentretien> getTypeentretiens() {
		return this.typeentretiens;
	}

	public void setTypeentretiens(Set<Typeentretien> typeentretiens) {
		this.typeentretiens = typeentretiens;
	}

}
