package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Typeentretien generated by hbm2java
 */
public class Typeentretien implements java.io.Serializable {

	private Integer numeroTypeE;
	private SousTypeEntretien sousTypeEntretien;
	private String nomTypeE;
	private Set<Entretien> entretiens = new HashSet<Entretien>(0);

	public Typeentretien() {
	}

	public Typeentretien(SousTypeEntretien sousTypeEntretien, String nomTypeE,
			Set<Entretien> entretiens) {
		this.sousTypeEntretien = sousTypeEntretien;
		this.nomTypeE = nomTypeE;
		this.entretiens = entretiens;
	}

	public Integer getNumeroTypeE() {
		return this.numeroTypeE;
	}

	public void setNumeroTypeE(Integer numeroTypeE) {
		this.numeroTypeE = numeroTypeE;
	}

	public SousTypeEntretien getSousTypeEntretien() {
		return this.sousTypeEntretien;
	}

	public void setSousTypeEntretien(SousTypeEntretien sousTypeEntretien) {
		this.sousTypeEntretien = sousTypeEntretien;
	}

	public String getNomTypeE() {
		return this.nomTypeE;
	}

	public void setNomTypeE(String nomTypeE) {
		this.nomTypeE = nomTypeE;
	}

	public Set<Entretien> getEntretiens() {
		return this.entretiens;
	}

	public void setEntretiens(Set<Entretien> entretiens) {
		this.entretiens = entretiens;
	}

}
