package com.pfe.persistance;

// Generated 29 févr. 2016 10:10:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Typepersonnel generated by hbm2java
 */
public class Typepersonnel implements java.io.Serializable {

	private Integer numeroTypeP;
	private String nomTypeP;
	private Set<Personnel> personnels = new HashSet<Personnel>(0);

	public Typepersonnel() {
	}

	public Typepersonnel(String nomTypeP, Set<Personnel> personnels) {
		this.nomTypeP = nomTypeP;
		this.personnels = personnels;
	}

	public Integer getNumeroTypeP() {
		return this.numeroTypeP;
	}

	public void setNumeroTypeP(Integer numeroTypeP) {
		this.numeroTypeP = numeroTypeP;
	}

	public String getNomTypeP() {
		return this.nomTypeP;
	}

	public void setNomTypeP(String nomTypeP) {
		this.nomTypeP = nomTypeP;
	}

	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

}
