package com.pfe.persistance;

// Generated 28 févr. 2016 18:08:45 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte {

	private Integer numeroCompte;
	private Personnel personnel;
	private String login;
	private String motDePasse;


	public Compte() {
	}

	public Compte(Personnel personnel, String login, String motDePasse,
			Set<Personnel> personnels) {
		this.personnel = personnel;
		this.login = login;
		this.motDePasse = motDePasse;
	
	}

	public Integer getNumeroCompte() {
		return this.numeroCompte;
	}

	public void setNumeroCompte(Integer numeroCompte) {
		this.numeroCompte = numeroCompte;
	}

	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result
				+ ((motDePasse == null) ? 0 : motDePasse.hashCode());
		result = prime * result
				+ ((numeroCompte == null) ? 0 : numeroCompte.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compte other = (Compte) obj;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (motDePasse == null) {
			if (other.motDePasse != null)
				return false;
		} else if (!motDePasse.equals(other.motDePasse))
			return false;
		if (numeroCompte == null) {
			if (other.numeroCompte != null)
				return false;
		} else if (!numeroCompte.equals(other.numeroCompte))
			return false;
		return true;
	}

}
