package com.pfe.persistance;

// Generated 28 févr. 2016 18:08:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Departement generated by hbm2java
 */
public class Departement{

	private Integer numeroDepartement;
	private String nomDepartement;
	private Set<Personnel> personnels2 = new HashSet<Personnel>(0);

	public Departement() {
	}

	public Departement(String nomDepartement, Set<Personnel> personnels2) {
		this.nomDepartement = nomDepartement;
		this.personnels2 = personnels2;
	}

	public Integer getNumeroDepartement() {
		return this.numeroDepartement;
	}

	public void setNumeroDepartement(Integer numeroDepartement) {
		this.numeroDepartement = numeroDepartement;
	}

	public String getNomDepartement() {
		return this.nomDepartement;
	}

	public void setNomDepartement(String nomDepartement) {
		this.nomDepartement = nomDepartement;
	}

	public Set<Personnel> getPersonnels2() {
		return this.personnels2;
	}

	public void setPersonnels2(Set<Personnel> personnels2) {
		this.personnels2 = personnels2;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((nomDepartement == null) ? 0 : nomDepartement.hashCode());
		result = prime
				* result
				+ ((numeroDepartement == null) ? 0 : numeroDepartement
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Departement other = (Departement) obj;
		if (nomDepartement == null) {
			if (other.nomDepartement != null)
				return false;
		} else if (!nomDepartement.equals(other.nomDepartement))
			return false;
		if (numeroDepartement == null) {
			if (other.numeroDepartement != null)
				return false;
		} else if (!numeroDepartement.equals(other.numeroDepartement))
			return false;
		return true;
	}

}
