package com.pfe.persistance;

// Generated 28 févr. 2016 18:08:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service {

	
	private Integer numeroService;
	private String nomService;
	private Set<Personnel> personnels3 = new HashSet<Personnel>(0);

	public Service() {
	}

	public Service(String nomService, Set<Personnel> personnels3) {
		this.nomService = nomService;
		this.personnels3 = personnels3;
	}

	public Integer getNumeroService() {
		return this.numeroService;
	}

	public void setNumeroService(Integer numeroService) {
		this.numeroService = numeroService;
	}

	public String getNomService() {
		return this.nomService;
	}

	public void setNomService(String nomService) {
		this.nomService = nomService;
	}

	public Set<Personnel> getPersonnels3() {
		return this.personnels3;
	}

	public void setPersonnels3(Set<Personnel> personnels3) {
		this.personnels3 = personnels3;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((nomService == null) ? 0 : nomService.hashCode());
		result = prime * result
				+ ((numeroService == null) ? 0 : numeroService.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Service other = (Service) obj;
		if (nomService == null) {
			if (other.nomService != null)
				return false;
		} else if (!nomService.equals(other.nomService))
			return false;
		if (numeroService == null) {
			if (other.numeroService != null)
				return false;
		} else if (!numeroService.equals(other.numeroService))
			return false;
		return true;
	}

}
